syntax = "proto3";

package repository.ranking;

option go_package = "github.com/Suinar/Bank-proto/proto/repository/exchange-ranking";

import "google/protobuf/timestamp.proto";

service RankingRepository {
  rpc GetRelativeRanking(GetRelativeRankingRequest) returns (Ranking);
  rpc GetAllRanking(GetAllRankingRequest) returns (RankingList);
}

message Ranking {
  int32 currency_iso_from = 1;
  int32 currency_iso_to = 2;

  google.protobuf.Timestamp date = 3;

  float rate_sell = 4;
  float rate_buy = 5;
  float rate_cross = 6;
}

message RankingList {
  repeated Ranking rankings = 1;
}

message GetRelativeRankingRequest {
  int32 currency_iso_from = 1;
  int32 currency_iso_to = 2;
}

message GetAllRankingRequest {
  int32 currency_iso_from = 1;
}
