// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.9
// source: exchange-rate/exchange-rate.proto

package exchange_ranking

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RankingRepository_GetRelativeRanking_FullMethodName = "/repository.ranking.RankingRepository/GetRelativeRanking"
	RankingRepository_GetAllRanking_FullMethodName      = "/repository.ranking.RankingRepository/GetAllRanking"
)

// RankingRepositoryClient is the client API for RankingRepository service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RankingRepositoryClient interface {
	GetRelativeRanking(ctx context.Context, in *GetRelativeRankingRequest, opts ...grpc.CallOption) (*RankingList, error)
	GetAllRanking(ctx context.Context, in *GetAllRankingRequest, opts ...grpc.CallOption) (*RankingList, error)
}

type rankingRepositoryClient struct {
	cc grpc.ClientConnInterface
}

func NewRankingRepositoryClient(cc grpc.ClientConnInterface) RankingRepositoryClient {
	return &rankingRepositoryClient{cc}
}

func (c *rankingRepositoryClient) GetRelativeRanking(ctx context.Context, in *GetRelativeRankingRequest, opts ...grpc.CallOption) (*RankingList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RankingList)
	err := c.cc.Invoke(ctx, RankingRepository_GetRelativeRanking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankingRepositoryClient) GetAllRanking(ctx context.Context, in *GetAllRankingRequest, opts ...grpc.CallOption) (*RankingList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RankingList)
	err := c.cc.Invoke(ctx, RankingRepository_GetAllRanking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RankingRepositoryServer is the server API for RankingRepository service.
// All implementations must embed UnimplementedRankingRepositoryServer
// for forward compatibility.
type RankingRepositoryServer interface {
	GetRelativeRanking(context.Context, *GetRelativeRankingRequest) (*RankingList, error)
	GetAllRanking(context.Context, *GetAllRankingRequest) (*RankingList, error)
	mustEmbedUnimplementedRankingRepositoryServer()
}

// UnimplementedRankingRepositoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRankingRepositoryServer struct{}

func (UnimplementedRankingRepositoryServer) GetRelativeRanking(context.Context, *GetRelativeRankingRequest) (*RankingList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRelativeRanking not implemented")
}
func (UnimplementedRankingRepositoryServer) GetAllRanking(context.Context, *GetAllRankingRequest) (*RankingList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllRanking not implemented")
}
func (UnimplementedRankingRepositoryServer) mustEmbedUnimplementedRankingRepositoryServer() {}
func (UnimplementedRankingRepositoryServer) testEmbeddedByValue()                           {}

// UnsafeRankingRepositoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RankingRepositoryServer will
// result in compilation errors.
type UnsafeRankingRepositoryServer interface {
	mustEmbedUnimplementedRankingRepositoryServer()
}

func RegisterRankingRepositoryServer(s grpc.ServiceRegistrar, srv RankingRepositoryServer) {
	// If the following call panics, it indicates UnimplementedRankingRepositoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RankingRepository_ServiceDesc, srv)
}

func _RankingRepository_GetRelativeRanking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRelativeRankingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingRepositoryServer).GetRelativeRanking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankingRepository_GetRelativeRanking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingRepositoryServer).GetRelativeRanking(ctx, req.(*GetRelativeRankingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankingRepository_GetAllRanking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRankingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingRepositoryServer).GetAllRanking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankingRepository_GetAllRanking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingRepositoryServer).GetAllRanking(ctx, req.(*GetAllRankingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RankingRepository_ServiceDesc is the grpc.ServiceDesc for RankingRepository service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RankingRepository_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "repository.ranking.RankingRepository",
	HandlerType: (*RankingRepositoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRelativeRanking",
			Handler:    _RankingRepository_GetRelativeRanking_Handler,
		},
		{
			MethodName: "GetAllRanking",
			Handler:    _RankingRepository_GetAllRanking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exchange-rate/exchange-rate.proto",
}
